adicionada função de destacar os contatos já adicionados
brunoreis/jam1 pull request #1
Opened 2023-02-07 00:55 UTC by joaosportugal

dentro da função de validação acrescentei a função de destacar os contatos caso o usuário queira adicionar um contato com nome, número ou ambos repetidos.

2023-02-07 11:59 UTC, brunoreis requested changes

2023-02-07 11:59 UTC, brunoreis commented on main.js
> +    function validate(contacts, formName, formNumber) {
porque adicionar todos esses métodos dentro da função `run`? E porque deixar o `getValue` de fora?

2023-02-07 11:59 UTC, brunoreis commented on main.js
> +        function highlightContact(caseOfRepeatedData) {
apesar da composição funcional ser um recurso  interessante tecnicamente, é sempre bom buscar uma api mais simples e direta. Ao invés de passar a função para buscar o índice, ficaria uma função mais clara e útil se ela já recebesse o índice ou algum id do contato.

2023-02-07 11:59 UTC, brunoreis commented on main.js
> +            if (contacts.find(bothEqual)) {
Na verdade algo está bem confuso aqui porque você passa o `caseOfRepeatedData`, mas logo abaixo usa todos os cases

2023-02-07 11:59 UTC, brunoreis commented on main.js
> +            highlightContact(bothEqual);
aqui já dava para pegar o índice com findIndex e passar o índice para o highlightContact

2023-02-07 11:59 UTC, brunoreis commented on main.js
> +            repeatedName.classList.remove('repeatedData');
essa parte de limpar as classes já existentes pode ser isolada em outra função

2023-02-07 12:08 UTC, brunoreis commented
Além dessas coisas que observei fica um desafio: mostrar os erros e highlights caso haja mais de um. Por exemplo, se eu colocar um nome que já existe e um número que já existe, eu quero ver as duas mensagens de erro e o nome e o número "highlighted".

2023-02-07 23:50 UTC, joaosportugal commented on main.js
> +    function validate(contacts, formName, formNumber) {
Penso que deixar tudo dessa função run() não seja realmente necessário nesse caso. Mas se houvesse muitas outras funcionalidades nessa aplicação seria interessante manter a função run() pra manter em function scope.

Resolvi retirar tudo da função run()

2023-02-07 23:52 UTC, joaosportugal commented on main.js
> +        function highlightContact(caseOfRepeatedData) {
Consegui escrever de uma forma mais clara.
Renomeei a função para highlight e nela eu passo dois argumentos, o primeiro é o index do contato repetido em questão e o segundo é quanto ao dado que está repetido, se é o nome ou se é o número, ou ambos.

2023-02-07 23:52 UTC, joaosportugal commented on main.js
> +            repeatedName.classList.remove('repeatedData');
consegui fazer isso e ficou bem melhor.

2023-02-07 23:53 UTC, joaosportugal commented on main.js
> +            if (contacts.find(bothEqual)) {
realmente estava bem confuso, eu tinha percebido mas não tinha encontrado outra forma... agora consegui separar as duas funções e passei o que seria caseOfRepeatedData como segundo parâmetro na função highlight

2023-02-07 23:53 UTC, joaosportugal commented on main.js
> +            highlightContact(bothEqual);
feito!

2023-02-08 13:07 UTC, joaosportugal commented
Parte do desafio foi realizado ao simplificar a função de highlight com o uso do método forEach()
Agora todos os nomes e números ficarão "highlighted" mesmo que o nome e/ou número esteja associado a contatos diferentes.

2023-02-08 15:29 UTC, joaosportugal commented
O desafio foi finalizado:
Mostrar os erros e highlights caso haja mais de um. Por exemplo, se eu colocar um nome que já existe e um número que já existe, eu quero ver as duas mensagens de erro e o nome e o número "highlighted".

2023-02-09 01:47 UTC, brunoreis commented on main.js
> +    function validate(contacts, formName, formNumber) {
concordo. Seja a run ou outra, manter o escopo dentro de uma função é uma boa prática. Quando você usar módulos do js, em projetos maiores, isso acontecerá automáticamente.

2023-02-09 02:36 UTC, brunoreis requested changes
No geral a PR está bem melhor. Já simplificou bastante e dá para avançar sem fazermos um call. Vamos trabalhar as coisas que comentei nessa PR. Vou colocar dois desafios, mas não aqui, e sim nas issues, para podermos fazer logo o merge dessa PR.

2023-02-09 02:36 UTC, brunoreis commented on main.js
> +    const errors = { name: 0, number: 0 };
é muito estranho inicializar esses valores com 0 e depois colocar uma string neles.

2023-02-09 02:36 UTC, brunoreis commented on index.html
> +        <p id="nameErrorMessage" class="errormessage"></p>
Talvez fosse melhor ter apenas um container aqui para você adicionar quantas mensagens de error quiser dentro dele.

2023-02-09 02:36 UTC, brunoreis commented on main.js
> +    if (contacts.find(sameName)) {
Isso aqui está repetido (linhas 33 a 36 e 38 a 41). Só a função e a mensagem de erro que são diferentes. É importante ir treinando o olho para reconhecer padrões.

2023-02-09 02:36 UTC, brunoreis commented on main.js
> +    const nameValidationResult = validationResults.name
acho melhor passar um array de n erros. Passar cada erro em um campo (name & number) não está fazendo muito sentido aqui e está deixando o código com mais coisa do que precisa.

2023-02-09 02:36 UTC, brunoreis commented on main.js
> +    if (contacts.find(sameName)) {
de maneira geral, pensando em separar dados da renderização eu faria o seguinte: 
1 - pegar todas as mensagens de erro
2 - mostrar todos os erros.

2023-02-09 02:36 UTC, brunoreis commented on main.js
> +    if (contacts.find(sameName)) {
Aqui você ainda não está passando para o highlight o que você quer destacar. A função highlight está verificando os erros por conta própria. O código de verificar se há coisas redundantes está redundante em si mesmo.

2023-02-09 02:36 UTC, brunoreis commented on main.js
> +    if (contacts.find(sameName)) {
O problema quando você faz isso, além da repetição do código, é que deixa de ter uma "single source of truth". 
Se um código ficar diferente do outro, o programa vai ficar inconsistente. Há o risco de mostrar os hightlights  sem os textos dos erros e vice-versa.

2023-02-09 13:49 UTC, joaosportugal commented on main.js
> +    const errors = { name: 0, number: 0 };
realmente... nem tinha necessidade.
Ajustei: agora errors = {} e onde eu esperava receber o valor 0 troquei por undefined

2023-02-21 14:20 UTC, joaosportugal commented on index.html
> +        <p id="nameErrorMessage" class="errormessage"></p>
feito!

2024-12-30 21:44 UTC, closed without merging